title: Jacob Swanson
url: "https://www.jacob-swanson.com"
encoding: utf-8
source: src
disable_disk_cache: true
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-last-modified-at
  - jekyll-sitemap
