title: Jacob Swanson
url: "https://www.jacob-swanson.com"
encoding: utf-8
exclude:
  - README.md
  - .htmlproofer-cache/
  - LICENSE
  - justfile
  - shell.nix
  - .gitignore
  - .idea/
  - .jekyll-cache/
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-last-modified-at
  - jekyll-sitemap
