title: Jacob Swanson
url: "https://www.jacob-swanson.com"
exclude:
  - README.md
  - .htmlproofer-cache
  - LICENSE
  - Makefile
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-last-modified-at
  - jekyll-sitemap
