# Variables
title: Jacob Swanson
author: Jacob Swanson
description: Jacob Swanson's personal website
email: jacob.swanson.n@gmail.com
baseurl:
url: http://www.jacob-swanson.com
github_username:  jacob-swanson
linkedin_username: jacob-swanson-1a1660a3

# Build settings
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
sass:
 sass_dir: _sass
 style: compressed
