title: Jacob Swanson
email: me@jacob-swanson.com
description: >- 
  Hi, I'm a software engineer living and working in Austin, TX.
url: "https://www.jacob-swanson.com"

sass:
        style: compressed
plugins:
  - jekyll-feed
  - jekyll-seo-tag
